name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Установка OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Настройка SSH для деплоя
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 45.138.158.251 >> ~/.ssh/known_hosts

      - name: Выполнение миграций и сбор статики
        run: |
          python manage.py migrate

      - name: Деплой на сервер
        run: |
          ssh root@45.138.158.251 
